FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1
ENV CACHE_DIR=/cache
WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY load_osm.py ./
CMD ["python", "load_osm.py"]